package HomeWorks.HW4.Ex5;

public enum Breed {
    FRENCH_BULLDOGS,
    LABRADOR_RETRIEVERS,
    GOLDEN_RETRIEVERS,
    GERMAN_SHEPHERD_DOGS,
    POODLES,
    BULLDOGS,
    ROTTWEILERS,
    BEAGLES,
    DACHSHUNDS,
    GERMAN_SHORTHAIRED_POINTERS;

}
