package edu05.Tests;
// Generated by CodiumAI

import edu05.task1.homework1_3;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;

public class homework1_3Test {


    // The program correctly prompts the user to enter 5 integer numbers.
    @Test
    public void test_promptUser() {
        // Arrange
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));
        String expectedOutput = "Enter 5 integer numbers:\n";

        // Act
        homework1_3.main(new String[]{});
        String actualOutput = outputStream.toString();

        // Assert
        assertEquals(expectedOutput, actualOutput);
    }

    // The program correctly reads in 5 integer numbers from the user.
    @Test
    public void test_readNumbers() {
        // Arrange
        ByteArrayInputStream inputStream = new ByteArrayInputStream("1 2 3 4 5".getBytes());
        System.setIn(inputStream);
        int[] expectedNumbers = {1, 2, 3, 4, 5};

        // Act
        homework1_3.main(new String[]{});

        // Assert
        assertArrayEquals(expectedNumbers, homework1_3.numbers);
    }

    // The program correctly handles the case where there are no positive numbers.
    @Test
    public void test_noPositiveNumbers() {
        // Arrange
        ByteArrayInputStream inputStream = new ByteArrayInputStream("-1 -2 -3 -4 -5".getBytes());
        System.setIn(inputStream);
        String expectedOutput = "Position of the second positive number: Not found\n" +
                "Minimum value: -5, and position: 5\n" +
                "Product of all entered even numbers: 1\n";
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));

        // Act
        homework1_3.main(new String[]{});
        String actualOutput = outputStream.toString();

        // Assert
        assertEquals(expectedOutput, actualOutput);
    }

    // The program correctly handles the case where there is only one positive number.
    @Test
    public void test_onePositiveNumber() {
        // Arrange
        ByteArrayInputStream inputStream = new ByteArrayInputStream("-1 -2 -3 4 -5".getBytes());
        System.setIn(inputStream);
        String expectedOutput = "Position of the second positive number: Not found\n" +
                "Minimum value: -5, and position: 5\n" +
                "Product of all entered even numbers: 4\n";
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));

        // Act
        homework1_3.main(new String[]{});
        String actualOutput = outputStream.toString();

        // Assert
        assertEquals(expectedOutput, actualOutput);
    }

    // The program correctly handles the case where all entered numbers are negative.
    @Test
    public void test_allNegativeNumbers() {
        // Arrange
        ByteArrayInputStream inputStream = new ByteArrayInputStream("-1 -2 -3 -4 -5".getBytes());
        System.setIn(inputStream);
        String expectedOutput = "Position of the second positive number: Not found\n" +
                "Minimum value: -5, and position: 5\n" +
                "Product of all entered even numbers: 1\n";
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));

        // Act
        homework1_3.main(new String[]{});
        String actualOutput = outputStream.toString();

        // Assert
        assertEquals(expectedOutput, actualOutput);
    }

}