package edu05.Tests;
// Generated by CodiumAI

import edu05.task1.homework1_2;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.InputMismatchException;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class homework1_2_mainTest {


    // Entering 10 positive numbers returns the sum of the first 5 positive values
    @Test
    public void test_entering_10_positive_numbers() {
        int[] arr = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
        int expectedSum = 1 + 2 + 3 + 4 + 5;

        // Redirect System.in to provide input values
        ByteArrayInputStream in = new ByteArrayInputStream("1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n".getBytes());
        System.setIn(in);

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));

        homework1_2.main(new String[]{});

        assertEquals("The sum of first 5 positive values is " + expectedSum, out.toString().trim());
    }

    // Entering a non-integer value throws an InputMismatchException
    @Test
    public void test_entering_non_integer_value() {
        // Redirect System.in to provide input values
        ByteArrayInputStream in = new ByteArrayInputStream("abc".getBytes());
        System.setIn(in);

        assertThrows(InputMismatchException.class, () -> {
            homework1_2.main(new String[]{});
        });
    }

}