package edu05.Tests;
// Generated by CodiumAI

import edu05.task4.Homework4;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class Homework4Test {


    // The program generates an array of 10 integers between 0 and 10 (inclusive).
    @Test
    public void test_generate_array() {
        Homework4 homework4 = new Homework4();
        int[] arr = homework4.generateArray();
        assertEquals(10, arr.length);
        for (int i = 0; i < arr.length; i++) {
            assertTrue(arr[i] >= 0 && arr[i] <= 10);
        }
    }

    // The program prompts the user to input a number between 0 and 10.
    @Test
    public void test_prompt_user_input() {
        Homework4 homework4 = new Homework4();
        // Mock user input
        ByteArrayInputStream inputStream = new ByteArrayInputStream("5".getBytes());
        System.setIn(inputStream);

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));

        homework4.promptUserInput();

        assertEquals("Input number (0-10) and try to guess what will be the output\n", outputStream.toString());
    }

    // The user inputs 0 and the correct number is also 0.
    @Test
    public void test_user_input_zero() {
        Homework4 homework4 = new Homework4();
        // Mock user input
        ByteArrayInputStream inputStream = new ByteArrayInputStream("0".getBytes());
        System.setIn(inputStream);

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));

        homework4.userInput();

        assertEquals("Wow, it's correct\n", outputStream.toString());
    }

    // The user inputs 10 and the correct number is also 10.
    @Test
    public void test_user_input_ten() {
        Homework4 homework4 = new Homework4();
        // Mock user input
        ByteArrayInputStream inputStream = new ByteArrayInputStream("10".getBytes());
        System.setIn(inputStream);

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));

        homework4.userInput();

        assertEquals("Wow, it's correct\n", outputStream.toString());
    }

    // The user inputs a negative number and the program handles the input appropriately.
    @Test
    public void test_user_input_negative() {
        Homework4 homework4 = new Homework4();
        // Mock user input
        ByteArrayInputStream inputStream = new ByteArrayInputStream("-5".getBytes());
        System.setIn(inputStream);

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));

        homework4.userInput();

        assertEquals("Too low, try again\n", outputStream.toString());
    }

}