package edu05.Tests;
// Generated by CodiumAI

import edu05.task1.homework1_1;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.Scanner;

import static java.lang.System.in;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;

public class homework1_1_mainTest {


    private static Scanner SCANNER = new Scanner(in);

    // The program correctly outputs the number of days in a month when a valid month number is inputted.
    @Test
    public void test_valid_month_number() {
        // Arrange
        int[] monthDays = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
        int monthNumber = 1;
        String expectedOutput = "Number of days in month is: 31";

        // Act
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));
        SCANNER = new Scanner(new ByteArrayInputStream(String.valueOf(monthNumber).getBytes()));
        homework1_1.main(null);
        String actualOutput = outputStream.toString().trim();

        // Assert
        assertEquals(expectedOutput, actualOutput);
    }

    // The program uses an array to store the number of days in each month.
    @Test
    public void test_month_days_array() {
        // Arrange
        int[] expectedMonthDays = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};

        // Act
        int[] actualMonthDays = homework1_1.monthDays;

        // Assert
        assertArrayEquals(expectedMonthDays, actualMonthDays);
    }

    // The program correctly handles invalid input outside the range of 1-12.
    @Test
    public void test_invalid_month_number() {
        // Arrange
        int monthNumber = 13;
        String expectedOutput = "Invalid month number.";

        // Act
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));
        SCANNER = new Scanner(new ByteArrayInputStream(String.valueOf(monthNumber).getBytes()));
        homework1_1.main(null);
        String actualOutput = outputStream.toString().trim();

        // Assert
        assertEquals(expectedOutput, actualOutput);
    }

    // The program correctly handles non-integer input.
    @Test
    public void test_non_integer_input() {
        // Arrange
        String nonIntegerInput = "abc";
        String expectedOutput = "Invalid month number.";

        // Act
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));
        SCANNER = new Scanner(new ByteArrayInputStream(nonIntegerInput.getBytes()));
        homework1_1.main(null);
        String actualOutput = outputStream.toString().trim();

        // Assert
        assertEquals(expectedOutput, actualOutput);
    }

    // The program correctly handles null input.
    @Test
    public void test_null_input() {
        // Arrange
        String expectedOutput = "Invalid month number.";

        // Act
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));
        SCANNER = new Scanner(new ByteArrayInputStream(null));
        homework1_1.main(null);
        String actualOutput = outputStream.toString().trim();

        // Assert
        assertEquals(expectedOutput, actualOutput);
    }

}