package edu05.Tests;
// Generated by CodiumAI

import edu05.task2.Homework02;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.PrintStream;

import static org.junit.Assert.assertEquals;

public class Homework02_mainTest {


    // User enters two positive integers and chooses not to repeat
    @Test
    public void test_positive_integers_no_repeat() {
        String input = "5\n6\nno\n";
        InputStream in = new ByteArrayInputStream(input.getBytes());
        System.setIn(in);

        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(outContent));

        Homework02.main(new String[]{});

        String expectedOutput = "Enter the first number:\n" +
                "Enter the second number:\n" +
                "Sum of the numbers: 11\n" +
                "Do you want to repeat? (yes/no)\n";

        assertEquals(expectedOutput, outContent.toString());

        System.setIn(System.in);
        System.setOut(originalOut);
    }

    // User enters two negative integers and chooses not to repeat
    @Test
    public void test_negative_integers_no_repeat() {
        String input = "-5\n-6\nno\n";
        InputStream in = new ByteArrayInputStream(input.getBytes());
        System.setIn(in);

        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(outContent));

        Homework02.main(new String[]{});

        String expectedOutput = "Enter the first number:\n" +
                "Enter the second number:\n" +
                "Sum of the numbers: -11\n" +
                "Do you want to repeat? (yes/no)\n";

        assertEquals(expectedOutput, outContent.toString());

        System.setIn(System.in);
        System.setOut(originalOut);
    }

    // User enters a non-integer value for the first number
    @Test
    public void test_non_integer_first_number() {
        String input = "abc\n6\nno\n";
        InputStream in = new ByteArrayInputStream(input.getBytes());
        System.setIn(in);

        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(outContent));

        Homework02.main(new String[]{});

        String expectedOutput = "Enter the first number:\n" +
                "Enter the second number:\n" +
                "Sum of the numbers: 6\n" +
                "Do you want to repeat? (yes/no)\n";

        assertEquals(expectedOutput, outContent.toString());

        System.setIn(System.in);
        System.setOut(originalOut);
    }

    // User enters a non-integer value for the second number
    @Test
    public void test_non_integer_second_number() {
        String input = "5\nxyz\nno\n";
        InputStream in = new ByteArrayInputStream(input.getBytes());
        System.setIn(in);

        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(outContent));

        Homework02.main(new String[]{});

        String expectedOutput = "Enter the first number:\n" +
                "Enter the second number:\n" +
                "Sum of the numbers: 5\n" +
                "Do you want to repeat? (yes/no)\n";

        assertEquals(expectedOutput, outContent.toString());

        System.setIn(System.in);
        System.setOut(originalOut);
    }

    // User enters a non-integer value for both numbers
    @Test
    public void test_non_integer_both_numbers() {
        String input = "abc\ndef\nno\n";
        InputStream in = new ByteArrayInputStream(input.getBytes());
        System.setIn(in);

        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(outContent));

        Homework02.main(new String[]{});

        String expectedOutput = "Enter the first number:\n" +
                "Enter the second number:\n" +
                "Sum of the numbers: 0\n" +
                "Do you want to repeat? (yes/no)\n";

        assertEquals(expectedOutput, outContent.toString());

        System.setIn(System.in);
        System.setOut(originalOut);
    }

}